apiVersion: v1
kind: Service
metadata:
  name: mediago-webapp
  namespace: app-web
spec:
  type: NodePort
  selector:
    app: mediago-webapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
    nodePort: 32080