apiVersion: v1
kind: Service
metadata:
  name: gitlab-web-nodeport
  namespace: gitlab-system
spec:
  type: NodePort
  selector:
    app.kubernetes.io/component: webservice
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 32180
    - name: https
      port: 443
      targetPort: 8443
      nodePort: 32143