apiVersion: v1
kind: Service
metadata:
  name: jenkins-nodeport
  namespace: devops-tools
spec:
  type: NodePort
  selector:
    app: jenkins-server
  ports:
    - protocol: TCP
      port: 50000
      targetPort: 50000
      nodePort: 32050