apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mediago-webapp
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-options: Force=true
spec:
  project: default
  source:
    repoURL: 'https://github.com/baonguyen3197/nhqb-website.git'
    targetRevision: HEAD
    path: 'manifests'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: app-web
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PruneLast=true
      - Replace=true
      - Force=true
  ignoreDifferences:
    - group: argoproj.io
      kind: Application
      jsonPointers:
        - /operation
operation:
  sync:
    syncStrategy:
      apply:
        force: true