apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mediago-webapp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/baonguyen3197/nhqb-website.git'
    targetRevision: HEAD
    path: 'manifests'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: app-web
  syncPolicy:
    automated:
      prune: true
      selfHeal: true