# Generated by Django 4.2.16 on 2024-10-25 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isLogin',
            field=models.BooleanField(default=False),
        ),
    ]
