apiVersion: apps/v1
kind: Deployment
metadata:
  name: mediago-webapp
  namespace: app-web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mediago-webapp
  template:
    metadata:
      labels:
        app: mediago-webapp
    spec:
      containers:
      - name: mediago-webapp
        image: index.docker.io/nhqb3197/nhqb-mysite:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: LDAP_SERVER_URI
          value: "ldap://10.10.100.95:389"
        - name: LDAP_BIND_DN
          value: "cn=admin,dc=example,dc=com"
        - name: LDAP_BIND_PASSWORD
          value: "ubuntu"
      imagePullSecrets:
      - name: dockerhub-creds