apiVersion: v1
kind: Service
metadata:
  labels:
    app: mediago-webapp
    argocd.argoproj.io/instance: mediago-webapp
  name: mediago-webapp
  namespace: app-web
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
      nodePort: 32080
  selector:
    app: mediago-webapp
  type: NodePort