apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: app-web
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: app-web
  name: pod-reader
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pods
  namespace: app-web
subjects:
- kind: ServiceAccount
  name: default
  namespace: app-web
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io