apiVersion: v1
kind: Service
metadata:
  name: yugabytedb-service
  namespace: yugabytedb
spec:
  type: NodePort
  selector:
    app: yb-tserver
    component: yugabytedb
  ports:
    - name: ysql
      port: 5433
      targetPort: 5433
      nodePort: 30433