apiVersion: v1
kind: Pod
metadata:
  name: kaniko
  namespace: devops-tools
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:latest
    args: [
           "--dockerfile=/workspace/Dockerfile",
           "--context=dir://workspace/",
           "--destination=nhqb3197/nhqb-mysite:latest"] # replace with your Docker Hub account
    volumeMounts:
    - name: kaniko-secret
      mountPath: /kaniko/.docker
    - name: kaniko-storage
      mountPath: /workspace
  restartPolicy: Never
  volumes:
  - name: kaniko-secret
    secret:
      secretName: regcred
      items:
      - key: .dockerconfigjson
        path: config.json
  - name: kaniko-storage
    persistentVolumeClaim:
      claimName: kaniko-pv-claim