apiVersion: v1
kind: Service
metadata:
  name: kaniko
  namespace: devops-tools
spec:
  selector:
    app: kaniko
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 32007
  type: NodePort