apiVersion: v1
kind: PersistentVolume
metadata:
  name: kaniko-pv-volume
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: /home/nhqb/Desktop/devops-tools/kaniko
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - nhqb-vm-1