apiVersion: v1
kind: Service
metadata:
  name: cyclops-ui-nodeport
  namespace: cyclops
spec:
  type: NodePort
  selector:
    app: cyclops-ui
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 80
      nodePort: 32300