# Generated by Django 4.2.16 on 2024-10-30 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('iata', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=255)),
                ('icao', models.CharField(max_length=4)),
                ('airport_name', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('airport_type', models.CharField(choices=[('International', 'International'), ('Domestic', 'Domestic')], default='Domestic', max_length=50)),
            ],
        ),
    ]
