# Generated by Django 4.2.16 on 2024-10-28 09:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('airport_id', models.IntegerField()),
                ('hotel_id', models.IntegerField()),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('location', models.CharField(max_length=255)),
                ('icao', models.CharField(max_length=4)),
                ('iata', models.CharField(max_length=3)),
                ('airport_name', models.CharField(max_length=255)),
            ],
        ),
    ]
