# Generated by Django 4.2.16 on 2024-10-28 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Airports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airport',
            name='hotel_id',
        ),
    ]
