# Generated by Django 4.2.16 on 2024-10-28 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Airports', '0002_remove_airport_hotel_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airport',
            name='airport_id',
        ),
    ]
