apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: observability
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 32003
  selector:
    app.kubernetes.io/name: grafana